### ISSUE TITLE
百度搜索指数、资讯指数、媒体指数爬取出现错误TypeError: string indices must be integers

### ISSUE THREAD

**Issue by sakura1379** [justinzm/gopup#20639]
File "D:\python\lib\site-packages\gopup\index\index_baidu.py", line 267, in baidu_search_index
    all_data = data["userIndexes"][0][type]["data"]
TypeError: string indices must be integers
请问这个是被反爬了吗？

**Comment by justinzm** [comment]
嗯 反爬了

**Comment by justinzm** [comment]
今天又好了 奇怪了 你再试试

**Comment by sakura1379** [comment]
好的好的谢谢~
